ALTER TABLE news_story ADD COLUMN IF NOT EXISTS kind VARCHAR(10) NOT NULL DEFAULT 'story';
ALTER TABLE news_story ADD COLUMN IF NOT EXISTS link_url VARCHAR(600);
ALTER TABLE news_story ADD COLUMN IF NOT EXISTS source VARCHAR(80);
